language: node_js
node_js:
  - "iojs"
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - git config --global user.name "shiliangL"
  - git config --global user.email "shiliangL@qq.com"

after_success:
  - npm docs:build
  - cd docs/.vuepress/dist
  - git add -A
  - git commit -m "update to travis-ci"
  - git push -f git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
